version: '3'

services:
  db:
    image: percona
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 9010:8080

  autobackup:
    build: docker-images/autobackup
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    #  - server-data:/data/server
    environment:
      DUPLICACY_BACKUP_OPTIONS: -threads 1 -stats
      BACKUP_NAME: ${BACKUP_NAME}
      BACKUP_LOCATION: ${BACKUP_LOCATION}
      BACKUP_SCHEDULE: ${BACKUP_SCHEDULE}
      B2_ID: ${B2_ID}
      B2_KEY: ${B2_KEY}
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  db-data: